enhance: Stepper use self Input and Button Component
ant-design/ant-design-mobile pull request #3984
Opened 2021-09-16 11:50 UTC by zqran

#3969 
增强：Stepper 调整为复用现有的 Input 和 Button 组件

2021-09-16 12:24 UTC, awmleer requested changes

2021-09-16 12:24 UTC, awmleer commented on src/components/stepper/stepper.less
>      &:disabled {
这个是不是去掉了，Input 应该是做了这些样式

2021-09-16 12:24 UTC, awmleer commented on src/components/stepper/stepper.less
> +  .@{class-prefix-stepper}-plus {
button 相关的这些样式应该也可以删掉很大一部分了～

2021-09-17 01:29 UTC, zqran commented on src/components/stepper/stepper.less
>      &:disabled {
已按照沟通后的内容，重新修改

2021-09-17 01:30 UTC, zqran commented on src/components/stepper/stepper.less
> +  .@{class-prefix-stepper}-plus {
已调整

2021-09-17 04:06 UTC, awmleer approved these changes
LGTM

2021-09-17 04:06 UTC, merged