fix: custom Navbar back icon failure
ant-design/ant-design-mobile pull request #3999
Opened 2021-09-19 12:45 UTC by p697

fix the problem of custom Navbar back icon

2021-09-19 14:04 UTC, awmleer requested changes

2021-09-19 14:04 UTC, awmleer commented on src/components/nav-bar/nav-bar.tsx
> -            <span className={`${classPrefix}-back-text`} aria-hidden='true'>
``className={`${classPrefix}-back-text`}`` 这里应该要保留的，莫非我没有写对应的 CSS……？

2021-09-19 14:04 UTC, awmleer commented on src/components/nav-bar/nav-bar.tsx
> -            {backArrow && (
不渲染图标的时候，这个 `span` 也不要渲染吧～这样更干净一些

2021-09-20 03:20 UTC, p697 commented on src/components/nav-bar/nav-bar.tsx
> -            <span className={`${classPrefix}-back-text`} aria-hidden='true'>
CSS里确实没有🙈 不过这里或许也没有必要写，如果要设置它的 `font-size` 的话，整个 left 区域都已经设置成了 15px，看上去不需要给 backText 单独设置

2021-09-20 03:20 UTC, p697 commented on src/components/nav-bar/nav-bar.tsx
> -            {backArrow && (
殴克克

2021-09-20 03:29 UTC, awmleer commented on src/components/nav-bar/nav-bar.tsx
> -            <span className={`${classPrefix}-back-text`} aria-hidden='true'>
ook 那这里就不加 className 了～

2021-09-20 07:42 UTC, awmleer approved these changes
LGTM

2021-09-20 07:42 UTC, merged