feat: Stepper add `onFocus` & `onBlur` prop
ant-design/ant-design-mobile pull request #4056
Opened 2021-09-27 12:24 UTC by jermyn626

#4052

2021-09-27 15:16 UTC, awmleer requested changes

2021-09-27 15:16 UTC, awmleer commented on src/components/stepper/demos/index.tsx
> +            console.log('获得焦点')
这里可以用 `Toast.show()`，体验会更好一些（下同）

2021-09-27 16:00 UTC, jermyn626 commented on src/components/stepper/demos/index.tsx
> +            console.log('获得焦点')
okk

2021-09-27 17:01 UTC, awmleer approved these changes

2021-09-27 17:01 UTC, merged

2021-09-28 02:55 UTC, rockux commented on src/components/stepper/stepper.tsx
> +          props.onFocus?.()
事件对象应该考虑传递出来吧

2021-09-28 03:23 UTC, awmleer commented on src/components/stepper/stepper.tsx
> +          props.onFocus?.()
嗯嗯的确可以把 event 暴露出来
@jermyn626

2021-09-28 05:40 UTC, jermyn626 commented on src/components/stepper/stepper.tsx
> +          props.onFocus?.()
好的，我晚点再加进去～

2021-09-28 09:33 UTC, jermyn626 commented on src/components/stepper/stepper.tsx
> +          props.onFocus?.()
#4065 已暴露