feat: (Dropdown) add `closeOnMaskClick` prop
ant-design/ant-design-mobile pull request #4313
Opened 2021-11-03 05:36 UTC by jacob-lcs

issue：https://github.com/ant-design/ant-design-mobile/issues/4310

为 `Dropdown` 组件新增 `closeOnMaskClick` 属性，默认为 `false`，表示是否开启「点击遮罩关闭下拉菜单」。

已添加 demo

2021-11-03 08:01 UTC, awmleer requested changes
默认为 `true` 吧～
其实之前 Dropdown 一直都是有点击遮罩层自动关闭的行为的，只不过中间有一次改动（stopPropagation 相关的逻辑调整）导致了 Dropdown 这里的关闭逻辑失效了

2021-11-03 08:01 UTC, awmleer commented
BTW，如果默认是 `true` 的话，demo 就可以删掉了

2021-11-03 08:25 UTC, jacob-lcs commented
> BTW，如果默认是 `true` 的话，demo 就可以删掉了

可以，我修改下~

2021-11-03 08:37 UTC, jacob-lcs commented
@awmleer 辛苦再 review 下~ 👀

2021-11-04 02:35 UTC, awmleer approved these changes
LGTM

2021-11-04 02:35 UTC, merged