feat: (DatePicker) add `week` and `weekday` precision
ant-design/ant-design-mobile pull request #4415
Opened 2021-11-23 07:30 UTC by p697

#4406

2021-11-28 03:34 UTC, awmleer requested changes

2021-11-28 03:34 UTC, awmleer commented on src/components/picker-view/index.en.md
> +| precision    | Precision                                                                                                                            | `'year' \| 'month' \| 'day' \| 'hour' \| 'minut
`weekday` 是工作日的意思，这里应该改为 `day-of-week`

2021-11-28 03:34 UTC, awmleer commented on src/components/picker-view/index.en.md
> +| precision    | Precision                                                                                                                            | `'year' \| 'month' \| 'day' \| 'hour' \| 'minut
其他地方同

2021-11-28 03:34 UTC, awmleer commented on src/components/date-picker/demos/index.tsx
> +      <DemoBlock title='周 - 工作日选择器'>
```suggestion
      <DemoBlock title='周选择器'>
```
就叫“周选择器”吧，工作日是指周一到周五的

2021-11-28 04:15 UTC, p697 commented on src/components/picker-view/index.en.md
> +| precision    | Precision                                                                                                                            | `'year' \| 'month' \| 'day' \| 'hour' \| 'minut
okk。内部的变量名就不改了吧，因为 dayjs 中就是用的 weekday，代码里可以统一一下，暴露给用户就是 day-of-week

2021-11-28 04:16 UTC, p697 commented on src/components/date-picker/demos/index.tsx
> +      <DemoBlock title='周 - 工作日选择器'>
hhh欧克

2021-11-28 07:27 UTC, awmleer commented on src/components/picker-view/index.en.md
> +| precision    | Precision                                                                                                                            | `'year' \| 'month' \| 'day' \| 'hour' \| 'minut
OK

2021-11-28 11:15 UTC, awmleer commented on src/components/date-picker/date-picker-utils.ts
> +dayjs.extend(isoWeeksInYear)
这里为啥用的是 iso 版本的插件……

2021-11-28 11:20 UTC, p697 commented on src/components/date-picker/date-picker-utils.ts
> +dayjs.extend(isoWeeksInYear)
因为 dayjs 中获取一年中有多少周只有 iso 的

https://dayjs.fenxianglu.cn/category/getset.html#%E5%B9%B4%E5%91%A8%E6%95%B0-iso

2021-12-01 01:37 UTC, p697 commented
刚刚提交了一个 [refactor](https://github.com/ant-design/ant-design-mobile/pull/4415/commits/e33f1dbfa7d18d9b6dd9b0edb48a9fcc597fa114)，将 `date-picker-utils` 拆成了 

`date-picker-date-utils` 和 `date-picker-week-utils`

然后现在的 `date-picker-utils` 用来判断当前 precision 然后分流到不同的 utils

2021-12-01 01:53 UTC, p697 commented
DatePickerView 里选择最后一周乱跳的问题修好了～

2021-12-01 04:17 UTC, awmleer approved these changes

2021-12-01 04:18 UTC, merged