fix: (ImageUploader) change the deleted logic to delete images by index
ant-design/ant-design-mobile pull request #4494
Opened 2021-12-02 07:49 UTC by liu-zhi-fei

fix [#4328](https://github.com/ant-design/ant-design-mobile/issues/4328) 
我发现删除图片是通过url，相同url图片就会出现BUG。

现在通过index删除。

2021-12-02 08:40 UTC, awmleer requested changes

2021-12-02 08:40 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +              setValue(value.filter((x, i) => i !== index))
不如直接用 splice？

```suggestion
              setValue([...value].splice(i, 1))
```

2021-12-02 08:45 UTC, liu-zhi-fei commented on src/components/image-uploader/image-uploader.tsx
> +              setValue(value.filter((x, i) => i !== index))
也可以，但是那样得写3行代码，splice的返回值是移除项组成的数组。

2021-12-03 04:07 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +              setValue(value.filter((x, i) => i !== index))
get，那按你的来

2021-12-03 04:07 UTC, awmleer approved these changes

2021-12-03 04:07 UTC, merged