feat: (switch) add css variables `--size` & `--border-width` & `--border-color`
ant-design/ant-design-mobile pull request #4496
Opened 2021-12-02 11:19 UTC by z1006

#4408 

重新调整了Dom结构，根据em特性来调整switch大小

新增了以下Css变量

| Name                   | Description      | Default                                |
| ----------------  | -------------- | -------------------------- |
| --size                   | 开关大小          | `30px`                                 |
| --border-width   | 边框宽度           | `1px`                                   |
| --border-color    | 边框颜色           | `#e5e5e5`                         |

2021-12-05 04:25 UTC, awmleer requested changes
似乎改之后的 Switch 大小和原来不一致了，边框、阴影什么的也不一样了，需要再完善一下～

新：
![image](https://user-images.githubusercontent.com/16526078/144733459-fd9b9014-ea21-4cc4-882d-63efd4928f2a.png)

旧：
![image](https://user-images.githubusercontent.com/16526078/144733507-c77087a7-bdf7-448e-8d10-82e83cc00b6f.png)

2021-12-06 01:56 UTC, z1006 commented
@awmleer 我对比了刚才的提交和rc2的版本，现在阴影和边框似乎是一致的了，但是大小还是有一些差异（之前是根据px写死的,现在是根据font-size自适应的,比例不太好控制）

2021-12-09 06:20 UTC, awmleer commented on src/components/switch/switch.less
> -  }
你这些都不能删掉的啊……这都是有动画的

我加回去吧

2021-12-09 06:31 UTC, awmleer commented
我在 846bb24b5 中重新写实现了一下，这个 PR 先关闭了哈

2021-12-09 06:31 UTC, closed without merging

2021-12-09 06:32 UTC, awmleer commented
用 font-size + em 来实现感觉不太优雅也不太可靠，而且有些情况下用户是需要分别设置宽和高的，所以拆成两个变量 `--width` 和 `--height` 了

2021-12-27 07:12 UTC, JackXM commented
--width 和 --height ,设置并不生效，只有--checked-color可以，白色那个圆球的大小并不是取变量的值，而是写死的 27px

2021-12-27 08:58 UTC, awmleer commented
> --width 和 --height ,设置并不生效，只有--checked-color可以，白色那个圆球的大小并不是取变量的值，而是写死的 27px

如果遇到了 bug，请提 issue 哈：https://github.com/ant-design/ant-design-mobile/issues/new/choose
顺便，请提供一下你版本号 & 核对一下发布日志

2021-12-27 09:26 UTC, JackXM commented
> > --width 和 --height ,设置并不生效，只有--checked-color可以，白色那个圆球的大小并不是取变量的值，而是写死的 27px
> 
> 如果遇到了 bug，请提 issue 哈：https://github.com/ant-design/ant-design-mobile/issues/new/choose 顺便，请提供一下你使用的 antd-mobile 的版本号 & 核对一下发布日志

版本号 "antd-mobile": "5.0.0-rc.2",
我看了下最新的 tag 是已经改好了的，所以就不提issue了，但是我们项目锁定在rc.2了，不知道要不要升上去。会不会有什么其他影响？
另外想问下卡晨大佬，「核对一下发布日志」是指什么意思？ 哈哈...

2021-12-28 02:27 UTC, awmleer commented
@JackXM 看起来是在 [rc.4](https://github.com/ant-design/ant-design-mobile/releases/tag/v5.0.0-rc.4) 新增的这些 CSS 变量
可以考虑升级一下哈，rc 版本是很稳定的，目前基本和正式版一样稳定可靠了，如果你没有用到“试验性组件”（在文档的组件列表中有一个分组是试验性），那么放心升级就可以了