fix: (Popover) stop `Popover.Menu` bubbling
ant-design/ant-design-mobile pull request #4705
Opened 2022-01-18 00:37 UTC by findmio

close #4702

2022-01-18 03:27 UTC, awmleer requested changes
这里不可以直接强制阻止冒泡的，可以参考一下 Popover 的实现，是有一个属性允许用户控制的

2022-01-18 10:09 UTC, awmleer commented on src/components/popover/pop-menu.tsx
> +  stopPropagation,
上面 Props 里需要定义出这个属性的，而且文档上也需要加一下……

2022-01-18 12:16 UTC, findmio commented on src/components/popover/pop-menu.tsx
> +  stopPropagation,
![image](https://user-images.githubusercontent.com/24765095/149935293-16f6d400-e540-4db1-ae30-7ee4ffb038c7.png)
这里的 `stopPropagation` 是继承自 `BasePopoverProps`，不用再加了吧

2022-01-19 02:22 UTC, awmleer commented on src/components/popover/pop-menu.tsx
> +  stopPropagation,
噢的确是的……我傻了

不过如果这样的话，那 Popover.Menu 是基于 Popover 的，现在 Popover 是默认已经有 stopPropagation 的处理，那 Popover.Menu 按理说什么都不需要做就可以 stopPropagation 了啊

我再仔细看下

2022-01-19 02:30 UTC, awmleer commented on src/components/popover/pop-menu.tsx
> +  stopPropagation,
我在这里改了一下 c4b6847cb ，发现是 Popover 的 `stopPropagation` 之前的实现逻辑有问题，现在 Popover.Menu 也已经正常了

2022-01-19 02:30 UTC, awmleer commented on src/components/popover/pop-menu.tsx
> +  stopPropagation,
这个 PR 我关闭了哈

2022-01-19 02:30 UTC, closed without merging