feat: (Picker) add `--button-font-size` and `--title-font-size`、`--item-font-size`
ant-design/ant-design-mobile pull request #4744
Opened 2022-01-27 03:59 UTC by yaogengzhu

#4734

2022-01-27 06:57 UTC, awmleer requested changes

2022-01-27 06:57 UTC, awmleer commented on src/components/picker/picker.tsx
> +  NativeProps<'--button-font-size | --title-font-size'>
这里写错了吧…… 应该是 `'--button-font-size' | '--title-font-size'`

2022-01-27 06:57 UTC, awmleer commented on src/components/picker/picker.less
> +    --button-font-size: 15px;
这样写不会有效的……你写个 demo 试试看，能不能调整样式

2022-01-27 06:57 UTC, awmleer commented on src/components/picker/index.zh.md
> +| --title-font-size  | title 字体大小，仅支持 px 单位           | `15px` | -        |
这里漏掉了 `--item-font-size`？英文文档同

2022-01-27 07:10 UTC, yaogengzhu commented on src/components/picker/index.zh.md
> +| --title-font-size  | title 字体大小，仅支持 px 单位           | `15px` | -        |
好的，我看下以上问题😋

2022-01-28 09:11 UTC, awmleer commented
@yaogengzhu 在你的基础上完善了一下，可以看看 diff 哈

2022-01-28 09:18 UTC, awmleer approved these changes

2022-01-28 09:20 UTC, merged

2022-01-28 09:36 UTC, yaogengzhu commented
> @yaogengzhu 在你的基础上完善了一下，可以看看 diff 哈

Get! 学习了