feat:(Calendar) add event listener when changed year or month (#4725)
ant-design/ant-design-mobile pull request #4786
Opened 2022-02-16 09:28 UTC by saxon-y

2022-02-16 10:19 UTC, awmleer requested changes

2022-02-16 10:19 UTC, awmleer commented on src/components/calendar/calendar.tsx
> +  onPageChange?: (current: number[]) => void
这里参数调整一下吧～改成 `year` 和 `month` 两个参数

2022-02-17 03:43 UTC, awmleer requested changes

2022-02-17 03:43 UTC, awmleer commented on src/components/calendar/demos/demo1.tsx
> +          }}
demo 这里开发的时候验证完了记得改回去哇，不然会对用户阅读代码有些干扰的

2022-02-17 03:45 UTC, saxon-y commented on src/components/calendar/calendar.tsx
> +    props?.onPageChange?.(current.year(), current.month() + 1)
这里搞错了 qaq

2022-02-17 03:45 UTC, saxon-y commented on src/components/calendar/demos/demo1.tsx
> +          }}
这里不用添加一个示例吗

2022-02-17 03:46 UTC, awmleer commented on src/components/calendar/demos/demo1.tsx
> +          }}
不用的……这个太简单了，不然示例的内容量要爆炸了

2022-02-17 03:48 UTC, saxon-y commented on src/components/calendar/demos/demo1.tsx
> +          }}
ok

2022-02-17 04:08 UTC, awmleer approved these changes
LGTM

2022-02-17 04:08 UTC, merged