enhance: (Form) add CSS variables border
ant-design/ant-design-mobile pull request #4823
Opened 2022-02-23 05:07 UTC by miracles1919

[#4819](https://github.com/ant-design/ant-design-mobile/issues/4819)

2022-02-23 05:49 UTC, saxon-y commented
> [#4819](https://github.com/ant-design/ant-design-mobile/issues/4819)

这样处理不好吧，我觉得可以新增一个 `Form.Group`  去处理这个问题

2022-02-23 06:36 UTC, miracles1919 commented
> 这样处理不好吧，我觉得可以新增一个 `Form.Group` 去处理这个问题

这样么？ @saxon-y 
```
<Form.Group>
  <Form>
    <Form.Item>
       <Input />
    <Form./Item>
  </Form>
</Form.Group>
```

2022-02-23 06:38 UTC, awmleer commented
现在是有 Form.Header 的，其实作用就是 Form.Group，用来在多组字段之间加个间距

2022-02-23 06:42 UTC, awmleer commented
issue 里回复了：https://github.com/ant-design/ant-design-mobile/issues/4819#issuecomment-1048488017

2022-02-23 06:43 UTC, saxon-y commented
```jsx
<Form>
  <Form.Group>
      <Form.Item>
         <Input />
      </Form.Item>
  </Form.Group>
  <Form.Group>
      <Form.Item>
         <Input />
      </Form.Item>
  </Form.Group>
</Form>
```
这样吧，属于同一个 form 实例 @miracles1919

2022-02-23 06:44 UTC, saxon-y commented
> 现在是有 Form.Header 的，其实作用就是 Form.Group，用来在多组字段之间加个间距

那这个不算 bug 呀， 用 `Form.Heade` 分割不就好了，可能需要完善下文档

2022-02-23 06:48 UTC, miracles1919 commented
... 我以为他们不想要里面的 border

2022-02-23 06:50 UTC, awmleer commented
@saxon-y 嗯嗯的确是可以补一些卡片模式和表单项分组的 demo，我去写一下

2022-02-23 06:55 UTC, saxon-y commented
> ... 我以为他们不想要里面的 border

可以先讨论下，在决定怎么处理，直接提 pr 不是一个好的选择

2022-02-23 07:17 UTC, awmleer commented
文档补了 1724485f6

2022-02-23 07:21 UTC, miracles1919 commented
> 可以先讨论下，在决定怎么处理，直接提 pr 不是一个好的选择

去哪讨论呢，对应的issue下么

2022-02-23 07:24 UTC, saxon-y commented
> > 可以先讨论下，在决定怎么处理，直接提 pr 不是一个好的选择
> 
> 去哪讨论呢，对应的issue下么

我觉得是，卡晨肯定会去看的

2022-02-23 07:28 UTC, awmleer requested changes

2022-02-23 07:28 UTC, awmleer commented on src/components/form/form-item.tsx
> +  } & NativeProps<'--border-inner'>
Form.Item 这里先不支持 `--border-inner` 了吧～ List.Item 现在也是不支持的，因为这个 inner 究竟是指上边还是下边的 border，其实容易有歧义

2022-02-23 07:28 UTC, awmleer commented on src/components/form/index.zh.md
> +| --border-inner  | 表单项底部的边框样式   | `solid 1px var(--adm-border-color)` |
改了下表述：

```suggestion
| --border-inner  | 表单项之间的边框样式   | `solid 1px var(--adm-border-color)` |
```

2022-02-23 07:28 UTC, awmleer commented on src/components/form/index.en.md
> +| --border-inner  | Border style of the form item   | `solid 1px var(--adm-border-color)` |
```suggestion
| --border-inner  | Border style between form items   | `solid 1px var(--adm-border-color)` |
```

2022-02-23 07:33 UTC, miracles1919 commented
> > > 可以先讨论下，在决定怎么处理，直接提 pr 不是一个好的选择
> > 
> > 
> > 去哪讨论呢，对应的issue下么
> 
> 我觉得是，卡晨肯定会去看的

ok

2022-02-24 03:02 UTC, awmleer approved these changes
LGTM

2022-02-24 03:03 UTC, merged