feat: refactor image-uploader beforeUpload function
ant-design/ant-design-mobile pull request #4879
Opened 2022-03-05 14:11 UTC by honorsuper

当前image-upload的beforeUpload方法接收一个files: File[]作为参数，这样方法中需要写上数组遍历的逻辑。如果逻辑中含有异步的操作，那么这个逻辑就会变的相对复杂。所以，参考rc-upload的做法，数组遍历的逻辑由组件来完成，beforeUplaod只需要传入单个文件的处理方法即可

2022-03-07 02:57 UTC, awmleer requested changes

2022-03-07 02:57 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +  beforeUpload?: (file: File, files: File[]) => Promise<File> | File
返回值改成是 `File | null` 吧，明确把 `null` 标出来，有些项目的 ts 会开 strictNullChecks 的

```suggestion
  beforeUpload?: (file: File, files: File[]) => Promise<File | null> | File | null
```

2022-03-07 02:57 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +  beforeUpload?: (file: File, files: File[]) => Promise<File> | File
还有就是这里的改动毕竟是出现了 break change，demo 里应该有用到这个属性的，需要一起调整一下

2022-03-07 02:57 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +    }
这里 catch 并不合理的，其实用户不应该在 `beforeUpload` 中 `throw error` 的，如果不想要这个文件，那应该`return null` 而不是 `throw error`

而且，如果这里 catch 了，会导致如果出现一些意外的报错，用户都感知不到，这样并不合理

2022-03-07 02:57 UTC, awmleer requested changes
噢还有，markdown 文档中的属性定义也要同步更新一下～

2022-03-07 04:52 UTC, honorsuper commented
> 噢还有，markdown 文档中的属性定义也要同步更新一下～

好的，我修改下

2022-03-07 04:58 UTC, honorsuper commented on src/components/image-uploader/image-uploader.tsx
> +  beforeUpload?: (file: File, files: File[]) => Promise<File> | File
已经修改完毕

2022-03-07 04:59 UTC, honorsuper commented on src/components/image-uploader/image-uploader.tsx
> +    }
好的

2022-03-08 05:57 UTC, awmleer approved these changes

2022-03-08 05:58 UTC, merged