feat: (cascader-view) add  isLeaf props
ant-design/ant-design-mobile pull request #4886
Opened 2022-03-08 08:10 UTC by yaogengzhu

#4881

2022-03-08 08:54 UTC, awmleer requested changes

2022-03-08 08:54 UTC, awmleer commented on src/components/cascader-view/use-cascader-value-extend.tsx
> +      isLeaf: generateExtends(val).isLeaf,
这里原来之所以用 `get` 是为了避免性能上的损耗，现在改成这样之后，其实就做不到类似于“懒计算”的效果了

所以还是得保留原来的用 `get` 的思路，分成 `generateItems` 和 `generateIsLeaf` 两个函数

的确是会稍微繁琐一点，但是我目前也没有想到更好的解法

2022-03-08 09:29 UTC, miracles1919 commented on src/components/cascader-view/use-cascader-value-extend.tsx
> +      isLeaf: generateExtends(val).isLeaf,
@awmleer 有没有可能将 `generateValueExtend` 放到组件中，`useCascaderValueExtend` 用来返回需要计算的 `Extend`，因为像 `isLeaf` 这样的状态在组件里很好判断，比如 `levels.length === val.length`

2022-03-08 09:39 UTC, miracles1919 commented on src/components/cascader-view/use-cascader-value-extend.tsx
> +      isLeaf: generateExtends(val).isLeaf,
还有是不是可以这样
```
const simple =  {} // 简单的 extend
const extend = {
  ...simple,
  get items(){} // 需要计算的 extend
}
```

2022-03-09 06:50 UTC, awmleer approved these changes
LGTM

2022-03-09 06:55 UTC, awmleer commented on src/components/cascader-view/use-cascader-value-extend.tsx
> +      isLeaf: generateExtends(val).isLeaf,
@miracles1919 听起来应该可以，不知道代码的组织上会不会遇到困难，可以来个 PR 一起试试～

2022-03-09 06:56 UTC, merged