feat: (ActionSheet) add `popupClassName` and `popupStyle`
ant-design/ant-design-mobile pull request #4910
Opened 2022-03-11 04:54 UTC by xiaoyao96

close #4901

2022-03-11 10:17 UTC, awmleer requested changes
文档需要更新一下～

2022-03-11 11:07 UTC, xiaoyao96 commented
ok，给忘了...回去我加下





------------------ Original ------------------
From: 卡晨 ***@***.***&gt;
Date: Fri,Mar 11,2022 6:17 PM
To: ant-design/ant-design-mobile ***@***.***&gt;
Cc: Leisure ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ant-design/ant-design-mobile] feat: (ActionSheet) add `popupClassName` and `popupStyle` (PR #4910)





 
@awmleer requested changes on this pull request.
 
文档需要更新一下～
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-03-11 13:19 UTC, xiaoyao96 commented
调整了下类型，和其他组件的maskClassName、maskStyle的规范一致，就不直接引用PopupProps了

2022-03-12 03:31 UTC, awmleer approved these changes

2022-03-12 03:31 UTC, merged