add property of `nativeElement` ref to use native input instance
ant-design/ant-design-mobile pull request #4951
Opened 2022-03-22 05:33 UTC by 1247748612

close: #4944

2022-03-22 06:15 UTC, awmleer requested changes

2022-03-22 06:15 UTC, awmleer commented on src/components/input/input.tsx
> +    nativeElement: nativeInputRef.current,
这里感觉得用 getter？不然的话初次渲染的时候，`nativeInputRef.current` 是 `null`

2022-03-22 06:15 UTC, awmleer commented on src/components/input/tests/input.test.tsx
> +    render(<Input ref={ref} value={undefined as any} />)
这里为啥要 `value={undefined as any}` 嘞？

2022-03-22 06:19 UTC, 1247748612 commented on src/components/input/tests/input.test.tsx
> +    render(<Input ref={ref} value={undefined as any} />)
上面copy下来的，为null有error，input不能接收为null的value，我不太明白你那个测试用例为啥允许为null

这里好像不需要这个参数，我改下

2022-03-22 06:47 UTC, 1247748612 commented on src/components/input/input.tsx
> +    nativeElement: nativeInputRef.current,
getter也是一样的结果

一开始整个ref都是为null的，等后续的render会使useImpertiveHandle重新执行此时nativeElement将会一定存在

2022-03-22 10:00 UTC, awmleer commented on src/components/input/input.tsx
> +    nativeElement: nativeInputRef.current,
如果 Input 只渲染一次的话，useImpertiveHandle 也就只会执行一次了，这个时候 nativeElement 应该是 null 的

2022-03-22 10:01 UTC, awmleer commented on src/components/input/input.tsx
> +    nativeElement: nativeInputRef.current,
估计没暴露出这个问题是因为 Input 渲染了多次

2022-03-23 06:54 UTC, awmleer commented
我直接改了哈

2022-03-23 06:54 UTC, awmleer approved these changes

2022-03-23 06:55 UTC, merged