feat: (Slider) support icon Props
ant-design/ant-design-mobile pull request #4957
Opened 2022-03-22 09:01 UTC by yaogengzhu

2022-03-22 09:05 UTC, yaogengzhu commented
#4954

2022-03-22 10:08 UTC, KingAmo commented
请问大概什么时候合并这个PR呢？ 或者有 rc版本吗，我现在就可以帮忙测试这个功能。

2022-03-22 10:23 UTC, awmleer requested changes

2022-03-22 10:23 UTC, awmleer commented on src/components/slider/index.zh.md
> +| icon          | 滑块的类型                                                                                      | `ReactNode`                                   | -                    |
这里是不是写错了，应该是：

```suggestion
| icon          | 滑块的图标                                                                                     | `ReactNode`                                   | -                    |
```

（英文文档同）

2022-03-22 10:23 UTC, awmleer commented on src/components/slider/thumb.tsx
> +          <ThumbIcon className={`${classPrefix}-thumb-icon`} />
自定义 `icon` 应该只能替换这个图标吧……外层的 thumb 容器还是要固定的

2022-03-22 10:27 UTC, yaogengzhu commented on src/components/slider/thumb.tsx
> +          <ThumbIcon className={`${classPrefix}-thumb-icon`} />
这位置之前我也是这么想的！ 我是把整个节点丢出去了，用户自定义更高，不知道是否有必要？

2022-03-23 02:25 UTC, awmleer commented on src/components/slider/thumb.tsx
> +          <ThumbIcon className={`${classPrefix}-thumb-icon`} />
如果让用户自定义的是整个 thumb，那对于一些简单的调整，用户写起来会挺复杂的，还得把整个 thumb 重写一遍，所以有利也有弊

我比较倾向于，renderIcon 就还是只控制 thumb 内部的那个图标，至于如果需要调整 thumb 的大小啊圆角啊什么的，可以组件暴露一些 CSS 变量出来，这样应该会对两种情况都比较舒适

2022-03-23 02:26 UTC, yaogengzhu commented on src/components/slider/thumb.tsx
> +          <ThumbIcon className={`${classPrefix}-thumb-icon`} />
> 如果让用户自定义的是整个 thumb，那对于一些简单的调整，用户写起来会挺复杂的，还得把整个 thumb 重写一遍，所以有利也有弊
> 
> 我比较倾向于，renderIcon 就还是只控制 thumb 内部的那个图标，至于如果需要调整 thumb 的大小啊圆角啊什么的，可以组件暴露一些 CSS 变量出来，这样应该会对两种情况都比较舒适

非常赞同你的看法！

2022-03-23 02:31 UTC, awmleer commented on src/components/slider/index.en.md
> +| icon          | The icon of slider                                                                                                                                       | `ReactNode`
这里默认值好像写错了诶

2022-03-23 02:32 UTC, awmleer commented on src/components/slider/index.en.md
> +| icon          | The icon of slider                                                                                                                                       | `ReactNode`
```suggestion
| icon          | The icon of slider                                                                                                                                       | `ReactNode`                                   |  -               |
```

2022-03-23 02:33 UTC, awmleer approved these changes

2022-03-23 02:33 UTC, merged