feat: (SwipeAction) add `stopPropagation` props
ant-design/ant-design-mobile pull request #4984
Opened 2022-03-28 08:05 UTC by findmio

2022-03-28 08:20 UTC, awmleer reviewed
是不是只需要对 `.adm-swipe-action-actions-left` 和 `.adm-swipe-action-actions-right` 这两个 div 加 `stopPropagation` 就可以了，现在这样改的话，会把 `children` 里的事件也阻断掉，这是预期行为么……？

2022-03-28 08:56 UTC, findmio commented
> 是不是只需要对 `.adm-swipe-action-actions-left` 和 `.adm-swipe-action-actions-right` 这两个 div 加 `stopPropagation` 就可以了，现在这样改的话，会把 `children` 里的事件也阻断掉，这是预期行为么……？

确实不妥。我改下

2022-03-28 09:58 UTC, awmleer requested changes

2022-03-28 09:58 UTC, awmleer commented on src/components/swipe-action/swipe-action.tsx
> +  stopPropagation: ['click'],
默认不能阻止的……不然会导致 break change 了

```suggestion
  stopPropagation: [],
```

（文档也要再调整下～

2022-03-28 10:01 UTC, findmio commented on src/components/swipe-action/swipe-action.tsx
> +  stopPropagation: ['click'],
ok

2022-03-29 02:55 UTC, awmleer approved these changes
LGTM

2022-03-29 02:56 UTC, merged