feat: (Ellipsis) add onClick props
ant-design/ant-design-mobile pull request #4986
Opened 2022-03-28 15:57 UTC by yaogengzhu

#4985

2022-03-29 03:00 UTC, awmleer commented on src/components/ellipsis/ellipsis.tsx
> +              e.stopPropagation()
这里不能默认 stopPropagation 的，之前加过一个属性 stopPropagationForActionButtons 专门用来控制这里的冒泡行为

如果默认阻止冒泡了，可能会导致一些问题（比如一些组件的 click away 自动关闭的逻辑会无法触发）

下同

2022-03-29 03:00 UTC, awmleer commented
https://github.com/ant-design/ant-design-mobile/issues/4985#issuecomment-1081349302

2022-03-29 03:13 UTC, yaogengzhu commented on src/components/ellipsis/ellipsis.tsx
> +              e.stopPropagation()
好的，还没注意到。我fix下

2022-03-29 03:22 UTC, awmleer commented on src/components/ellipsis/ellipsis.tsx
> +              e.stopPropagation()
先不用改了吧～我们先等等看原 issue 作者的回复吧

我感觉他想要的不是整体的 onClick 事件，可能他希望是要一个类似 onContentClick 的事件，只有点击文字内容部分的时候才触发

2022-03-29 03:26 UTC, yaogengzhu commented on src/components/ellipsis/ellipsis.tsx
> +              e.stopPropagation()
ok

2022-03-30 02:21 UTC, awmleer requested changes

2022-03-30 02:21 UTC, awmleer commented on src/components/ellipsis/ellipsis.tsx
> +          props?.onContentClick(e)
这里 props 应该不用 `?.` 的

```suggestion
          props.onContentClick(e)
```

2022-03-30 02:22 UTC, awmleer approved these changes

2022-03-30 02:22 UTC, merged