refactor: improve collapse implementation
ant-design/ant-design-mobile pull request #5017
Opened 2022-04-01 11:27 UTC by 1247748612

fix: #5004

2022-04-05 13:06 UTC, awmleer requested changes
既然都用 context 了，为啥还要 `toArray` 处理 `children` 啊？当然也可以反过来说，既然都 `toArray` 处理 `children`，为啥还需要用 context？

我试了一下，这样写是不 work 的，看起来 context 好像没起到作用……？

```jsx
<Collapse defaultActiveKey={['1']}>
  <div>
    <Collapse.Panel key='1' title='第一项'>
      {mockContents[0]}
    </Collapse.Panel>
  </div>
  <Collapse.Panel key='2' title='第二项'>
    {mockContents[1]}
  </Collapse.Panel>
  <Collapse.Panel key='3' title='第三项'>
    {mockContents[2]}
  </Collapse.Panel>
</Collapse>
```

2022-04-05 13:09 UTC, awmleer commented
我比较倾向于去掉 context，然后允许用户在 children 中套 React.Fragment，也就是 #4466 这个 issue 中所说的问题

如果加 context 的话，用户可能会在 `Collapse.Panel` 外套很多奇奇怪怪的东西，甚至可能套个 portal 什么的，到最后有可能会出来很多很多的问题，所以还不如索性就统一限制一下（和 Form、IndexBar 什么的都保持一致）

2022-04-05 13:09 UTC, 1247748612 commented
> 既然都用 context 了，为啥还要 `toArray` 处理 `children` 啊？当然也可以反过来说，既然都 `toArray` 处理 `children`，为啥还需要用 context？
> 
> 
> 
> 我试了一下，这样写是不 work 的，看起来 context 好像没起到作用……？
> 
> 
> 
> ```jsx
> 
> <Collapse defaultActiveKey={['1']}>
> 
>   <div>
> 
>     <Collapse.Panel key='1' title='第一项'>
> 
>       {mockContents[0]}
> 
>     </Collapse.Panel>
> 
>   </div>
> 
>   <Collapse.Panel key='2' title='第二项'>
> 
>     {mockContents[1]}
> 
>   </Collapse.Panel>
> 
>   <Collapse.Panel key='3' title='第三项'>
> 
>     {mockContents[2]}
> 
>   </Collapse.Panel>
> 
> </Collapse>
> 
> ```

主要还是因为key这个属性是react的属性，并不会传递到组件到props里导致拿不到key也就拿不到分辨唯一的属性了

只支持fragement包裹

2022-04-05 13:15 UTC, awmleer commented
> 主要还是因为key这个属性是react的属性，并不会传递到组件到props里导致拿不到key也就拿不到分辨唯一的属性了

噢 get 那的确，那要不把 context 去掉吧？

2022-04-05 13:17 UTC, awmleer commented
你用 context 是不是为了解决 props 传递的问题啊？比如 CollapsePanel 需要有 `onClick` 或者 `onChange` 之类的属性，但是又不希望把这个属性暴露给用户

2022-04-05 13:18 UTC, awmleer commented
如果是这样的话，那感觉可以 `Collapse.Panel` 是一个假的组件：

```tsx
const Panel: FC<PanelProps> = () => null
```

然后对 `children` 处理之后，实际渲染的是另一个内部的组件（不会暴露给用户）：

```tsx
const InnerPanel: FC<SomeInnerProps>
```

2022-04-05 14:07 UTC, 1247748612 commented
> 我比较倾向于去掉 context，然后允许用户在 children 中套 React.Fragment，也就是 #4466 这个 issue 中所说的问题
> 
> 如果加 context 的话，用户可能会在 `Collapse.Panel` 外套很多奇奇怪怪的东西，甚至可能套个 portal 什么的，到最后有可能会出来很多很多的问题，所以还不如索性就统一限制一下（和 Form、IndexBar 什么的都保持一致）

我也是比较支持只允许套React.Fragment的，目前的现状，采用优雅的方式也只能支持到这样

2022-04-06 03:20 UTC, awmleer commented
我这样实现了： bc88def0

感觉其实很简单呀……就是在之前基础上的一个小调整，也不需要 `toArray` 和 context 的

2022-04-06 03:20 UTC, closed without merging

2022-04-06 03:20 UTC, awmleer commented
anyway，感谢贡献～