feat: support react18
ant-design/ant-design-mobile pull request #5046
Opened 2022-04-08 08:09 UTC by miracles1919

- [x] 对 `ReactDOM.render` 和 `ReactDOM.unmountComponentAtNode` 增加了适配方法，移植自 [antd](https://github.com/ant-design/ant-design/blob/master/components/_util/compatible.ts)
- [x] 改造了下 renderToBody
- [ ] FC Props add `children` definition

> [[RFC] React 18 and types-only breaking changes #46691
](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691) remove implicitly typed children from React.FC (and the corresponding overload of React.memo)

to be continued...

2022-04-09 04:33 UTC, awmleer commented on package.json
> +    "@types/react": "^17.0.44",
诶这里的 `@types/react` 咋还是 17

2022-04-09 06:53 UTC, miracles1919 commented on package.json
> +    "@types/react": "^17.0.44",
前几天我更新的时候还是 17，这两天才更新的 18..  😮

2022-04-09 09:37 UTC, awmleer commented on src/utils/compatible.ts
> +  createRoot = require('react-dom/client').createRoot
```suggestion
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  createRoot = require('react-dom/client').createRoot
```

2022-04-09 09:41 UTC, awmleer approved these changes
LGTM

等 antd 先发布吧～它们发完没问题了我再来合并
顺便我也还得抽空再看看 React 18 strict mode 下的适配问题

2022-04-09 09:45 UTC, awmleer requested changes
emm…… CI 挂了，看起来还有些组件漏加了 `children` 定义

2022-04-09 09:52 UTC, miracles1919 commented
> emm…… CI 挂了，看起来还有些组件漏加了 `children` 定义

我看到一个 Form 里的

rc-field-form 里的 `children` 是 `RenderProps | React.ReactNode`

`traverseReactNode` 方法里的 `children` 是 ` React.ReactNode`

2022-04-09 10:00 UTC, miracles1919 commented
其他的我晚点在看看 ~

2022-04-09 14:34 UTC, awmleer commented
嗯嗯不急～反正还要等 antd

2022-05-07 03:48 UTC, awmleer commented
话说这个 PR 是不是可以再搞一下了 🤔 antd 已经发布了兼容 React 18 的逻辑

2022-05-07 05:39 UTC, miracles1919 commented
ok 下午搞下

2022-05-07 09:40 UTC, miracles1919 commented
`@testing-library/user-event` 这个库升到最新版 upload test 会有问题，似乎跟这个 [issue](https://github.com/testing-library/user-event/issues/940#issuecomment-1108483516) 有关，就先不动了

2022-05-08 09:55 UTC, awmleer commented
> `@testing-library/user-event` 这个库升到最新版 upload test 会有问题，似乎跟这个 [issue](https://github.com/testing-library/user-event/issues/940#issuecomment-1108483516) 有关，就先不动了

ok～

2022-05-08 10:35 UTC, awmleer requested changes

2022-05-08 10:35 UTC, awmleer commented on src/components/action-sheet/tests/__snapshots__/action-sheet.test.tsx.snap
> +  class=""
奇怪……这个 className 怎么没了，这个会影响滚动锁定的，可以参考 src/utils/use-lock-scroll.ts

2022-05-08 10:46 UTC, awmleer commented on src/components/action-sheet/tests/__snapshots__/action-sheet.test.tsx.snap
> +  class=""
不过我在 demo 上试了一下是行为正常的，而且 body 上是有 `adm-overflow-hidden` 这个 class：

<img width="407" alt="image" src="https://user-images.githubusercontent.com/16526078/167292579-c0993e39-df1f-477d-ad3d-14c1fa081219.png">

这么看的话感觉是 test 的问题？🤔

2022-05-09 08:16 UTC, awmleer commented on src/components/floating-bubble/floating-bubble.tsx
> +    // @ts-ignore
这个好像不用加 ignore，我删掉之后好像也没有报错

2022-05-09 08:16 UTC, awmleer commented on src/components/pull-to-refresh/pull-to-refresh.tsx
> +      eventOptions: supportsPassive ? { passive: false } : undefined,
这里也是，我这里不改也是正常的

2022-05-09 08:19 UTC, awmleer commented on src/components/action-sheet/tests/__snapshots__/action-sheet.test.tsx.snap
> +      style="transform: translate(0, 68.58969969000708%);"
这里倒是会 test 的时候报错，看起来好像每次运行的值都不一样：

![image](https://user-images.githubusercontent.com/16526078/167369165-89b900fe-0929-40f7-94d5-988df2229991.png)

2022-05-09 08:21 UTC, miracles1919 commented
之前更新 yarn.lock 的时候，`@use-gesture/react` 更了一个小版本 `10.2.10` ->  `10.2.11`，重新 install 的话，会有一些 ts 类型错误

2022-05-10 01:57 UTC, awmleer commented
eventOptions 应该是 ts 的 dom 类型定义更新导致的，不过 passive 保险起见还是得兼容一下这种情况：

<img width="673" alt="image" src="https://user-images.githubusercontent.com/16526078/167526979-22eeca0e-0630-465f-a6ea-6b7cb9362bd8.png">

我改成这样了，还稍微温和一些：

```ts
eventOptions: supportsPassive
  ? { passive: false }
  : (false as unknown as AddEventListenerOptions),
```

2022-05-10 01:59 UTC, awmleer commented
floating bubble 的 bounds 我也改成单行里写 any 里，比 ts-ignore 还稍微好一些，感觉这里应该是 use-gesture 的问题，我查了它文档，useDrag 的 bounds 是支持 ref 的：

> Drag bounds
> Since v10 and for the drag gesture only, bounds can be a React ref or an HTMLElement, in which case the dragged element will be constrained to the element bounds (calculated with getBoundingClientRect).

2022-05-10 02:00 UTC, awmleer approved these changes
LGTM 总算可以合并了 🎉

2022-05-10 02:00 UTC, merged

2022-05-12 05:54 UTC, lbyupup commented
> LGTM 总算可以合并了 🎉
大佬，请问组件还是会报children属性没有，这个得把antd升级到哪个版本可以解决

2022-05-12 07:38 UTC, awmleer commented
@lbyupup 看下发布日志哈，里面有写，不确定的话，直接升级到最新版也可以