feat: (calendar) support custome of navigation label
ant-design/ant-design-mobile pull request #5149
Opened 2022-05-06 13:52 UTC by yaogengzhu

#5148

2022-05-07 01:18 UTC, awmleer requested changes

2022-05-07 01:18 UTC, awmleer commented on src/components/calendar/calendar.tsx
> +  next2Label?: React.ReactNode
调整下名字吧……

```
prevYearButton
prevMonthButton
nextYearButton
nextMonthButton
```

2022-05-07 01:19 UTC, yaogengzhu commented on src/components/calendar/calendar.tsx
> +  next2Label?: React.ReactNode
ok.

2022-05-07 01:38 UTC, awmleer requested changes

2022-05-07 01:38 UTC, awmleer commented on src/components/calendar/demos/demo1.tsx
> +        </DemoDescription>
这个描述看起来应该删掉

2022-05-07 01:40 UTC, yaogengzhu commented on src/components/calendar/demos/demo1.tsx
> +        </DemoDescription>
是的～ 我改下！

2022-05-08 10:52 UTC, awmleer approved these changes
LGTM

2022-05-08 10:53 UTC, merged