test(Toast): add some tests
ant-design/ant-design-mobile pull request #5292
Opened 2022-06-08 09:08 UTC by miracles1919

2022-06-09 09:14 UTC, awmleer requested changes

2022-06-09 09:14 UTC, awmleer commented on src/components/toast/toast.tsx
> +        return <CheckOutline className={`${classPrefix}-success`} />
这里还是加个 icon 的前缀吧～

```suggestion
        return <CheckOutline className={`${classPrefix}-icon-success`} />
```

下同

2022-06-09 15:07 UTC, miracles1919 commented on src/components/toast/toast.tsx
> +        return <CheckOutline className={`${classPrefix}-success`} />
ok

2022-06-10 02:45 UTC, awmleer approved these changes
LGTM

2022-06-10 02:46 UTC, merged