refactor(Popup): render with `ShouldRender`
ant-design/ant-design-mobile pull request #5338
Opened 2022-06-16 06:41 UTC by miracles1919

#5155

2022-06-17 07:06 UTC, awmleer requested changes

2022-06-17 07:06 UTC, awmleer commented on src/components/action-sheet/action-sheet.tsx
> +  'afterClose' | 'getContainer' | 'destroyOnClose' | 'forceRender'
`destroyOnClose` 和 `forceRender` 这样算是新增的属性了，文档需要调整一下～

2022-06-17 07:06 UTC, awmleer commented on src/components/cascader/cascader.tsx
> +  | 'forceRender'
这里也一样，需要调整一下文档

2022-06-17 07:06 UTC, awmleer commented on src/components/number-keyboard/number-keyboard.tsx
> +  | 'forceRender'
这里也一样，需要调整一下文档

2022-06-17 07:18 UTC, miracles1919 commented
我想着先把代码 review 了再改文档

2022-06-17 07:37 UTC, awmleer commented
噢噢那代码感觉没问题的

2022-06-17 08:55 UTC, miracles1919 commented
改完之后 Picker 指令式调用的 test 会挂，我先把 case 拆了

```
// ❎
test('case 1', async () => {
    await Picker.prompt(...)
    fireEvent.click('取消')
    expect(...)
    
    fireEvent.click('确定')
    expect(...)
}) 

```

test case 拆开就行 
```
// ✅
await Picker.prompt(...)
fireEvent.click('取消')
expect(...)
```
```
// ✅
await Picker.prompt(...)
fireEvent.click('确定')
expect(...)
```

2022-06-17 10:27 UTC, xiaoyao96 commented
我把这个pr拉下来发现，最后两个用例过不了。

倒数第二个用例中用到了fakerTimers，我实测会超时...原因可能是fackerTimers不会让定时器执行，需要手动执行timers，如`jest.runAllTimers`等

我之前写用例有实测过，当Pikcer.prompt执行后使用`jest.getTimerCount()`的值为2，说明在渲染Picker时，有两个定时器被执行了。

顺着这个线索，我发现如果Picker.prompt不传defaultValue。Picker - PickerView - Wheel 会在渲染时向上更新innerValue，而PickerView有两个hook的deps含有innerValue，刚好是这两个定时器：

```ts
useEffect(() => {
    if (props.value === innerValue) return
    const timeout = window.setTimeout(() => {
      if (props.value !== undefined && props.value !== innerValue) {
        setInnerValue(props.value)
      }
    }, 1000)
    return () => {
      window.clearTimeout(timeout)
    }
  }, [props.value, innerValue])

  const extend = useColumnsExtend(props.columns, innerValue)
  const columns = extend.columns

  useDebounceEffect(
    () => {
      if (props.value === innerValue) return
      props.onChange?.(innerValue, extend)
    },
    [innerValue],
    {
      wait: 0,
      leading: false,
      trailing: true,
    }
  )
```

这里逻辑比较复杂，1秒的定时器预期应该多次render时被清理，实际不会被执行，但用例里如果用`jest.runAllTimers`却会让1秒的定时器陷入死循环.. 但使用`jest.advanceTimersToNextTimer`则正常。

后面我就放弃了fakerTimers，用了await act(() => sleep(0)) 发现可以完美解决这个定时器的问题。

2022-06-18 09:57 UTC, awmleer approved these changes
LGTM

2022-06-18 09:58 UTC, awmleer commented
感觉后面可以直接在 tests 的 `sleep` 工具函数里加上 `act`，这样就不需要 `await act(() => sleep(100))` 了，可以直接 `await sleep(100)`，借鉴的 `fireEvent.click` 的思路

2022-06-18 09:59 UTC, merged

2022-06-18 14:34 UTC, miracles1919 commented
> 感觉后面可以直接在 tests 的 `sleep` 工具函数里加上 `act`，这样就不需要 `await act(() => sleep(100))` 了，可以直接 `await sleep(100)`，借鉴的 `fireEvent.click` 的思路

我看了下其实有 `actSleep`， 看样子还是放在 `sleep` 比较好

2022-06-18 15:06 UTC, miracles1919 commented
试了下，实际不太行... 

```jsx
render(
  <Button 
    onClick={async () => {
        await sleep(100)
    }}
  >Button</Button/>)
fireEvent.click(getByText('Button'))
```
本身 `render` 和 `fireEvent` 已经有 `act` wrap 了，这样会导致 `act` 嵌套多个 `act`

> Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.

2022-06-19 02:34 UTC, awmleer commented
这样啊……那算了