feat(List): list support nativeElement ref
ant-design/ant-design-mobile pull request #5369
Opened 2022-06-21 10:14 UTC by yaogengzhu

#5368

2022-06-21 11:00 UTC, GOWxx reviewed
[chore: add some test](https://github.com/ant-design/ant-design-mobile/pull/5369/commits/b1a0392769a13ab9285f2fd49a6343b9f239a9b6)

test: add some test

2022-06-22 03:12 UTC, awmleer commented
@yaogengzhu 之后可以写 `close #xxxx` 这样，这样 PR 合并之后会自动关闭 issue 的，例如[这个 PR](https://github.com/ant-design/ant-design-mobile/pull/5362)

2022-06-22 03:19 UTC, awmleer requested changes

2022-06-22 03:19 UTC, awmleer commented on src/components/list/list.tsx
> +  const nativeListRef = useRef<HTMLDivElement>(null)
这里感觉叫 `nativeElementRef` 更合适一些……

```suggestion
  const nativeElementRef = useRef<HTMLDivElement>(null)
```

2022-06-22 03:19 UTC, awmleer commented on src/components/list/list.tsx
> +export type ListRef = {
`ListRef` 这个类型需要在 `index.ts` 中 export 一下，可以参考下别的组件～

2022-06-22 03:20 UTC, yaogengzhu commented on src/components/list/list.tsx
> +export type ListRef = {
好的，晚些时候我处理下

2022-06-22 09:16 UTC, merged