feat(swipeAction): add onActionsReveal props
ant-design/ant-design-mobile pull request #5484
Opened 2022-07-19 12:03 UTC by LadyChatterleyLover

feat(swipeAction): add onActionsReveal props

2022-07-19 13:07 UTC, zqran requested changes

2022-07-19 13:18 UTC, zqran commented
https://github.com/ant-design/ant-design-mobile/blob/bafad206d6cdbacbd45ea699918ddda8cfa5e326/src/components/swipe-action/swipe-action.tsx#L141-L142

指令式展示 action 操作按钮时，也应该触发 `onActionsReveal`

2022-07-19 14:53 UTC, LadyChatterleyLover commented
@zqran 已经添加了哈

2022-07-20 01:55 UTC, zqran commented
<img width="791" alt="image" src="https://user-images.githubusercontent.com/15389209/179878951-1d7c1563-9c47-4f74-a0ae-6425219083a6.png">
上面的文档内容也修改下吧~

2022-07-20 03:15 UTC, LadyChatterleyLover commented
@zqran 文档已经修改了哈，

2022-07-21 07:39 UTC, awmleer approved these changes

2022-07-21 09:56 UTC, zqran commented on src/components/swipe-action/swipe-action.tsx
> +          p.onActionsReveal?.('right')
这块的逻辑，可以这样处理不

```tsx
useImperativeHandle(ref, () => ({
  show: (side: 'left' | 'right' = 'right') => {
    if (side === 'right') {
      api.start({
        x: -getRightWidth(),
      })
    } else if (side === 'left') {
      api.start({
        x: getLeftWidth(),
      })
    }
    // 这边，提到外面
    p.onActionsReveal?.(side)
  },
  close,
}))
```

2022-07-21 10:08 UTC, awmleer commented on src/components/swipe-action/swipe-action.tsx
> +          p.onActionsReveal?.('right')
@LadyChatterleyLover 你最近有空调整一下这里不？

2022-07-21 10:48 UTC, LadyChatterleyLover commented
好的，晚上调整一下，



发自我的iPhone


------------------ Original ------------------
From: zqran ***@***.***&gt;
Date: Thu,Jul 21,2022 5:56 PM
To: ant-design/ant-design-mobile ***@***.***&gt;
Cc: luopei ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ant-design/ant-design-mobile] feat(SwipeAction): add`onActionsReveal` prop (PR #5484)





 
@zqran commented on this pull request.
 
 
In src/components/swipe-action/swipe-action.tsx:
 &gt; @@ -141,10 +146,12 @@ export const SwipeAction = forwardRef<SwipeActionRef, SwipeActionProps&gt;(      useImperativeHandle(ref, () =&gt; ({        show: (side: 'left' | 'right' = 'right') =&gt; {          if (side === 'right') { +          p.onActionsReveal?.('right')  
这块的逻辑，可以这样处理不
 useImperativeHandle(ref, () =&gt; ({   show: (side: 'left' | 'right' = 'right') =&gt; {     if (side === 'right') {       api.start({         x: -getRightWidth(),       })     } else if (side === 'left') {       api.start({         x: getLeftWidth(),       })     }     // 这边，提到外面     p.onActionsReveal?.(side)   },   close, }))
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2022-07-21 10:48 UTC, LadyChatterleyLover commented
好的，晚上调整一下，



发自我的iPhone


------------------ Original ------------------
From: 卡晨 ***@***.***&gt;
Date: Thu,Jul 21,2022 6:09 PM
To: ant-design/ant-design-mobile ***@***.***&gt;
Cc: luopei ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ant-design/ant-design-mobile] feat(SwipeAction): add`onActionsReveal` prop (PR #5484)





 
@awmleer commented on this pull request.
 
 
In src/components/swipe-action/swipe-action.tsx:
 &gt; @@ -141,10 +146,12 @@ export const SwipeAction = forwardRef<SwipeActionRef, SwipeActionProps&gt;(      useImperativeHandle(ref, () =&gt; ({        show: (side: 'left' | 'right' = 'right') =&gt; {          if (side === 'right') { +          p.onActionsReveal?.('right')  
@LadyChatterleyLover 你最近有空调整一下这里不？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-07-21 11:10 UTC, LadyChatterleyLover commented
@zqran @awmleer 已经调整了哈，

2022-07-22 02:28 UTC, awmleer approved these changes
LGTM

2022-07-22 02:29 UTC, merged