fix(hook): fix Hook useResizeEffect,avoid ResizeObserver loop limit e…
ant-design/ant-design-mobile pull request #5491
Opened 2022-07-21 08:42 UTC by MuxinFeng

https://github.com/ant-design/ant-design-mobile/issues/5459

2022-07-21 08:59 UTC, MuxinFeng commented
问题描述在引用文献里讲的很清楚了。
简单来说的话，就是 fn(target) 没能在一帧内处理完毕，所以会抛出个提示，但是不会有其他影响。window.requestAnimationFrame 保证了在下次重绘开始前，必须要把函数执行完（应该是指动画计算）。

2022-07-21 10:07 UTC, awmleer commented on src/utils/use-resize-effect.tsx
> +        window.requestAnimationFrame(() => fn(target));
是不是还得对应地加个 `cancelAnimationFrame`？

2022-07-21 10:47 UTC, MuxinFeng commented on src/utils/use-resize-effect.tsx
> +        window.requestAnimationFrame(() => fn(target));
加上了，因为从 2012 年后的各种浏览器都开始支持这个属性了，就没做兼容性了

2022-07-21 10:48 UTC, MuxinFeng commented on src/utils/use-resize-effect.tsx
> +        window.requestAnimationFrame(() => fn(target));
https://caniuse.com/?search=requestAnimationFrame

2022-07-21 10:48 UTC, MuxinFeng commented on src/utils/use-resize-effect.tsx
> +        window.requestAnimationFrame(() => fn(target));
https://caniuse.com/?search=cancelAnimationFrame

2022-07-22 02:30 UTC, awmleer commented on src/utils/use-resize-effect.tsx
> +        window.requestAnimationFrame(() => fn(target));
嗯嗯我之前也查过，兼容性是OK的

2022-07-22 02:44 UTC, awmleer requested changes

2022-07-22 02:44 UTC, awmleer commented on src/utils/use-resize-effect.tsx
> +        window.cancelAnimationFrame(AnimationFramerRes)
这个实现有问题的吧……？应该是取消上一次的 callback

2022-07-22 02:59 UTC, MuxinFeng commented on src/utils/use-resize-effect.tsx
> +        window.cancelAnimationFrame(AnimationFramerRes)
我再去研究下哈

2022-07-22 04:05 UTC, MuxinFeng commented on src/utils/use-resize-effect.tsx
> +        window.cancelAnimationFrame(AnimationFramerRes)
调整了一下，感谢 review

2022-07-22 05:49 UTC, MuxinFeng commented on src/utils/use-resize-effect.tsx
> +        window.cancelAnimationFrame(AnimationFramerRes)
主要是吧 cancelAnimationFrame 的调用时机调整了一下，参考这个https://github.com/nolimits4web/swiper/pull/5441/files

2022-07-25 06:41 UTC, awmleer approved these changes

2022-07-25 06:42 UTC, merged