feat(Footer): add footer component
ant-design/ant-design-mobile pull request #5611
Opened 2022-08-23 09:13 UTC by liangchaofei

add footer component

2022-08-26 12:22 UTC, zqran requested changes

2022-08-26 12:22 UTC, zqran commented on src/components/footer/footer.less
> +  background-color: --background-color;
```suggestion
  background-color: var(--background-color);
```

2022-08-26 12:22 UTC, zqran commented on src/components/footer/footer.tsx
> +                  href={link?.value}
```suggestion
                  href={link.value}
```
这边也没有必要 `?.` 吧？还有后面的一些内容，以及 `chips` 里面的很多地方也都可以去掉 `?.`

2022-08-26 12:22 UTC, zqran commented on src/components/footer/footer.tsx
> +          {links?.map((link: LinkItem, index: number) => {
```suggestion
          {links.map((link: LinkItem, index: number) => {
```

这边不需要 `?.` 吧？

2022-08-26 12:22 UTC, zqran commented on src/components/footer/footer.tsx
> +    e: React.MouseEvent<HTMLAnchorElement, globalThis.MouseEvent>
```suggestion
    e: React.MouseEvent<HTMLAnchorElement, MouseEvent>
```
这边为什么要用 `globalThis.MouseEvent`？

2022-08-26 12:22 UTC, zqran commented on src/components/footer/footer.tsx
> +  onChipClick?: (item: ReactNode | any, index: number) => void
```suggestion
  onChipClick?: (item: ChipItem, index: number) => void
```
感觉直接这样就行啦？为什么要联合 `any`? 下面的 `onLinkClick` 也是一样~

2022-08-26 12:22 UTC, zqran commented on src/components/footer/index.en.md
> +# Footer 页脚
```suggestion
# Footer
```

2022-08-30 15:34 UTC, liangchaofei commented
已修复，辛苦再帮忙review下

2022-09-13 09:14 UTC, awmleer commented
@zqran @miracles1919 我在原来的基础上又改了一波～求再看看

2022-09-13 09:17 UTC, zqran approved these changes

2022-09-13 10:25 UTC, miracles1919 commented on src/components/footer/demos/demo1.tsx
> +      <DemoBlock title='label是自定义DOM'>
```suggestion
      <DemoBlock title='label 是自定义 DOM'>
```
格式可以改下

2022-09-13 10:25 UTC, miracles1919 commented on src/components/footer/footer.tsx
> +import Tag, { TagProps } from '../tag'
Tag 没用到吧，TagProps 应该也不需要

2022-09-13 10:38 UTC, miracles1919 commented
我也改了一波

- 删除了 `tagProps`
- 优化了下 demo 文案，删除了重复的 demo
- 更新了中英文文档的标点

@awmleer 再看看

2022-09-14 02:12 UTC, awmleer approved these changes

2022-09-14 02:13 UTC, merged