feat(ImageUploader): optimize image preview memory
ant-design/ant-design-mobile pull request #5627
Opened 2022-09-01 02:06 UTC by zqran

fix #5625

2022-09-09 01:56 UTC, awmleer requested changes

2022-09-09 01:56 UTC, awmleer commented on src/components/image-uploader/preview-item.tsx
> +  })
发现有个问题是，如果组件渲染的过程中， url 或者 file 发生了变化，那么旧的 object url 还是没有被清理，所以感觉这里还是得用 useLayoutEffect 来处理了？

2022-09-09 03:54 UTC, zqran commented on src/components/image-uploader/preview-item.tsx
> +  })
图片上传过程中，渲染的是 `tasks` 对应的 `<PreviewItem />`，上传完成后 tasks 数组清空。此时，渲染的是 `value` 中的 `<PreviewItem />`。
图片上传过程中，由于还没有 url，此时会根据上传的文件，`URL.createObjectURL(file)`。当图片上传完成后，由于 tasks 数组清空，此时，会卸载 `<PreviewItem />` 组件，来释放 `createObjectURL(file)`  的内存。

如果 url 发生改变，说明图片已经上传完成，已经释放了  `createObjectURL(file)`  的内存。
如果 file 发生改变，上传过程中，当前正在上传的 file 会改变吗？ @awmleer

2022-09-13 10:11 UTC, awmleer requested changes

2022-09-13 10:11 UTC, awmleer commented on src/components/image-uploader/preview-item.tsx
>    }, [url, file])
突然发现，是不是直接这样就可以了：

```tsx
const src = useMemo(() => {
   if (url) {
     return url
   }
   if (file) {
     return URL.createObjectURL(file)
   }
   return ''
 }, [url, file])
 
useEffect(() => {
  return () => {
    URL.revokeObjectURL(src)
  }
}, [src])
```

2022-09-13 10:12 UTC, awmleer commented on src/components/image-uploader/preview-item.tsx
> +  })
感觉极端情况下是有可能的……？🤔用户前一个上传任务完成的时候，刚好添加了一个新的上传任务，就出现了图片内容的替换，但是组件没有销毁？

2022-09-13 10:16 UTC, zqran commented on src/components/image-uploader/preview-item.tsx
>    }, [url, file])
这样，`revokeObjectURL` 的可能是 url，而不是 `createObjectURL` 返回的内容。

2022-09-13 10:20 UTC, zqran commented on src/components/image-uploader/preview-item.tsx
> +  })
新的上传的任务会加到 tasks 数组里面去，列表渲染的时候，好像不会影响到已有上传内容~  不过还是这么处理吧，万一有想不到的边界情况呢~

2022-09-14 02:20 UTC, awmleer commented on src/components/image-uploader/preview-item.tsx
>    }, [url, file])
对的，但是好像即便这样调用了，也不会有实际的影响，浏览器应该会直接忽略掉？

2022-09-15 02:50 UTC, awmleer approved these changes

2022-09-15 02:50 UTC, merged