fix: 修复switch在hd模式下宽度抖动
ant-design/ant-design-mobile pull request #5630
Opened 2022-09-01 12:57 UTC by UnicornLinYI

2022-09-09 01:58 UTC, awmleer requested changes

2022-09-09 01:58 UTC, awmleer commented on src/components/switch/switch.less
> +    width: var(--width);
这里 `width` 应该不能写死的，像 demo 中的这个例子：

<img width="237" alt="image" src="https://user-images.githubusercontent.com/16526078/189256317-3b1ea3db-287f-4c36-adb2-b6f3e2b86e24.png">

宽度是根据内容被自动撑起来的

2022-09-09 04:06 UTC, zqran commented
@UnicornLinYI 你可以在使用 `Switch` 组件时，根据你的需要，来手动设置其宽度。比如：

```tsx
<Switch style={{ 'width': 'var(--width)' }} />
```

2022-09-13 05:26 UTC, awmleer commented
PR 那我关闭了～

2022-09-13 05:26 UTC, closed without merging