feat(ImageUploader): add `onUploadQueueChange` prop
ant-design/ant-design-mobile pull request #5640
Opened 2022-09-03 13:16 UTC by zqran

fix #5608

2022-09-13 10:18 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +  onUploadQueueChange?: (tasks: Task[]) => void
又考虑了一下，Task 其实是个组件内部的定义，感觉完全暴露出去之后还真不太好……后面就不能很随意的调整 Task 里的字段了，要不我们还是先基础一点的只暴露一个长度出来？

```ts
onUploadQueueChange?: (queueLength: number) => void
```

2022-09-13 10:23 UTC, zqran commented on src/components/image-uploader/image-uploader.tsx
> +  onUploadQueueChange?: (tasks: Task[]) => void
或者我们可以从 Task 中映射出一些信息，而不是直接将 Task 暴露呢？

2022-09-14 02:06 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +  onUploadQueueChange?: (tasks: Task[]) => void
嗯嗯这也是个思路～

2022-09-14 02:08 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +  onUploadQueueChange?: (tasks: Task[]) => void
那感觉可以先只暴露 `id` 和 `status`？这样用户就完全足够获取到上传中的文件有几个、上传失败的有几个了

2022-09-14 05:30 UTC, zqran commented on src/components/image-uploader/image-uploader.tsx
> +  onUploadQueueChange?: (tasks: Task[]) => void
get~ 那我按照这种方式来修改下

2022-09-15 02:46 UTC, awmleer requested changes

2022-09-15 02:46 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +export type Task = {
这个是不是不用 export 了

2022-09-15 02:46 UTC, awmleer commented on src/components/image-uploader/image-uploader.tsx
> +export type UploadTask = Pick<Task, 'id' | 'status'>
这个类型需要在 `index.tsx` 里 re-export 一下～

2022-09-15 04:29 UTC, zqran commented on src/components/image-uploader/image-uploader.tsx
> +export type Task = {
是的~ 忘了去掉了

2022-09-15 04:29 UTC, zqran commented on src/components/image-uploader/image-uploader.tsx
> +export type UploadTask = Pick<Task, 'id' | 'status'>
get

2022-09-15 06:52 UTC, awmleer approved these changes
LGTM

2022-09-15 06:52 UTC, merged