Feat calendar/0908
ant-design/ant-design-mobile pull request #5650
Opened 2022-09-08 08:44 UTC by wine-fall

- 想要禁止日历的翻页，比如当前的需求限制用户只能看当前月份，无法实现，试过一些方法，详见：https://github.com/ant-design/ant-design-mobile/discussions/5649
- 新增两个 props：prevFarthestDate，nextFarthestDate。分别表示**最前**能看到的日期，和**最后**能看到的日期，该区间为左闭右闭，也即为 [prevFarthestDate, nextFarthestDate]

2022-09-08 08:55 UTC, wine-fall commented
```
if (action === 'subtract' && props.prevFarthestDate) {
      const prevFarthestDate = dayjs(props.prevFarthestDate)
      if (nxtCurrent.isBefore(prevFarthestDate, type)) {
       // 也许还要传个监听函数，在此return之前调用，方便用户加一些toast
      // 想过直接用 onPageChange，但是与其名称不符（并没有change）
        return
      }
 }
```

2022-09-13 09:16 UTC, awmleer commented
诶 `prevFarthestDate` `nextFarthestDate` 和 `min` `max` 有啥区别……？

2022-09-13 09:26 UTC, awmleer commented
感觉还有另一种思路，现在用户处于哪一页这个状态 `page` 其实是封装在组件内部没有开放出来的，如果把这个改成可受控的，那用户就可以手动传入一个固定的 `page`，并且拦截 `onPageChange`

2022-09-14 08:13 UTC, wine-fall commented
> onPageChange
1. `min` 和 `max` 是控制当前日期是否 `disable` 的，而 `prevFarthestDate`  和 `nextFarthestDate` 是控制日历能否切换到这个日期，也就是控制当前日期能否 **看见**
2. 拦截 `onPageChange` 有啥用？`onPageChange`是监听`current`变化的，它并没有改变 `current`

2022-09-14 09:54 UTC, awmleer commented
1. 噢 get 了，那确实不一样
2. `page` 是个内部状态，之前没有通过属性暴露出来的

2022-09-14 10:03 UTC, wine-fall commented
> 2. `page` 是个内部状态，之前没有通过属性暴露出来的

没太明白 `page` 这个 **内部状态** 是什么意思

我看 `page` 只有 `jumpTo` 这个暴露给父组件的函数用了，而且这是用户自己传进去的

``` typescript
type Page = { month: number; year: number }
jumpTo: (page: Page | ((page: Page) => Page)) => void
```

我只看到有 `current` 
``` typescript
  const [current, setCurrent] = useState(() =>
    dayjs(dateRange ? dateRange[0] : today).date(1)
  )
```
我看逻辑就是 `setCurrent` -> 触发更新 -> 再跑一遍 `renderCells` 用新的 `current` 画出新的日历

2022-09-14 10:17 UTC, awmleer commented
噢对不起我说错了，内部状态是叫 `current`

这么看下来的话，你现在的实现方案已经是挺合理的了~

不过命名上直接叫 `minPage` `maxPage`？而且因为是只需要月和日，其实类型用 `Page` 就可以了：

```ts
type Props = {
  minPage: Page
  maxPage: Page
}
```

2022-09-15 07:25 UTC, awmleer requested changes
文档也要更新一下～ `index.zh.md` 和 `index.en.md`

2022-09-15 07:25 UTC, wine-fall commented
好的，按照你的建议做了修改。
不过这个两个props并不会阻止 `jumpTo` 和 `jumpToToday`

2022-09-15 08:35 UTC, awmleer commented
OK

2022-09-19 09:41 UTC, awmleer commented on src/components/calendar/calendar.en.md
> +| ----------------- | ------------------------------------------------------------------------------- | -----------------------------------------------------------------------------------------------
```suggestion
| ----------------- | ------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------ | ---------- |
```

2022-09-19 09:41 UTC, awmleer approved these changes

2022-09-19 09:42 UTC, merged