Feat/nested swiper
ant-design/ant-design-mobile pull request #5669
Opened 2022-09-16 10:35 UTC by HuberTRoy

fix #5663 

移动端`use-gesture`里的`event.stopPropagation`似乎并不会阻止冒泡。

增加了一个组件uid和模块级的uid变量来标识当前组件。

2022-09-19 09:50 UTC, awmleer requested changes

2022-09-19 09:50 UTC, awmleer commented on src/components/swiper/swiper.tsx
> +    const [uid] = useState(uuidv4())
这里感觉其实完全不需要用 uuid 呀，直接用空对象就好了啊 😅 `{}`

2022-09-19 10:49 UTC, HuberTRoy commented on src/components/swiper/swiper.tsx
> +    const [uid] = useState(uuidv4())
@awmleer 

给跪了大佬，完全没想到这个，之前也不想加依赖，但想了很久不知道有什么简单还可以保证无冲突的= =。果然听君一席话胜读十年书。大佬🐂。

2022-09-20 08:45 UTC, awmleer commented on src/components/swiper/swiper.tsx
> +    const [uid] = useState(uuidv4())
没有没有～我只是这种逻辑写多了罢了

整体上你的思路很巧妙的～我一开始想的都是怎么阻止事件冒泡，没有想到其实只需要像你这样加个锁就可以了 👍

2022-09-20 09:18 UTC, zqran approved these changes

2022-09-20 09:18 UTC, zqran commented on src/components/swiper/swiper.tsx
> +let currentUid: undefined | {}
这个思路，6 啊

2022-09-20 09:19 UTC, awmleer approved these changes
@HuberTRoy 在你的基础上微调了一下逻辑顺序，别的地方没问题了～

2022-09-20 09:19 UTC, merged

2022-09-20 09:32 UTC, miracles1919 commented
学习一下

2022-09-20 10:04 UTC, HuberTRoy commented
开心O(∩_∩)O~~。

2023-02-24 08:41 UTC, lunhui1994 commented
还需要阻止冒泡了么？怎么看起来没生效。更新的5.28.1版本