fix(ellipsis): content could be undefined
ant-design/ant-design-mobile pull request #5727
Opened 2022-10-11 09:55 UTC by afc163

close #5726

2022-10-11 10:01 UTC, awmleer requested changes

2022-10-11 10:01 UTC, awmleer commented on src/components/ellipsis/ellipsis.tsx
> +  const chars = useMemo(() => runes(props.content ?? ''), [props.content])
其实直接在上面 24 行的 `defaultProps` 里加上 `content: ''` 应该就可以了

2022-10-11 10:22 UTC, awmleer commented on src/components/ellipsis/ellipsis.tsx
> +  const chars = useMemo(() => runes(props.content ?? ''), [props.content])
`defaultProps` 里加了之后组件里面就不用判断了～ 😅 `mergeProps` 会确保 `props.content` 为 `undefined` 的时候会 fallback 到 `defaultProps` 里的 `''`

2022-10-11 12:12 UTC, awmleer approved these changes
LGTM

2022-10-11 13:57 UTC, merged

2022-10-13 06:48 UTC, KingAmo commented
请问什么时候发新版本呢