feat(ImageUploader): add  and other css props
ant-design/ant-design-mobile pull request #5728
Opened 2022-10-11 10:10 UTC by MuxinFeng

[relate issue](https://github.com/ant-design/ant-design-mobile/issues/5702)

本次 PR 内容：
1. 支持 grid 布局（参考 Selector 实现），其中单个图片组件的尺寸通过 column 和 gap 计算得出
2. 添加了 grid 的基本的样式 props
3. 添加了中英文参数说明
4. 添加了一个 demo

2022-10-13 03:05 UTC, zqran requested changes

2022-10-13 03:10 UTC, zqran commented
@MuxinFeng 我优化了一下，样式和结构，你看下是否有没考虑到的地方~

2022-10-14 07:21 UTC, MuxinFeng commented on src/components/image-uploader/index.en.md
> +| columns             | 行展示数                                                                                                                                                                 | `number`
嗯嗯，我改下哈～

2022-10-14 07:42 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.less
> +  ---gap: var(--gap);
这个是按照 selector 那边的写法，大佬能给点正确的写法的 demo 或者关键词吗

2022-10-14 08:07 UTC, zqran commented on src/components/image-uploader/image-uploader.less
> +  ---gap: var(--gap);
我有一个想法：就是直接去掉该组件的根元素 `<div className={classPrefix}>`，直接用 `Grid` 或 `Space` 作为该组件的根节点。这样就不需要 `---gap` 这种额外的 CSS 变量了，这边的样式会简化很多。不知道去掉现在的根元素，会不会导致额外的问题。

2022-10-14 09:06 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.less
> +  ---gap: var(--gap);
会不会引起央视污染

2022-10-17 11:17 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.less
> +  ---gap: var(--gap);
我有两个想法哈，求大佬给指点一下 @zqran 
1. 一般组件的根节点的 className 一般都是组件名开头的，这算是个样式命名规范吧。
2. 如果没有根节点限定范围，我担心会跟其他用`Grid`或`Space`组件的地方产生样式冲突（污染）。

2022-10-18 01:44 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.less
> +  ---gap: var(--gap);
我懂您意思了，我这边试试看是否会有意外影响

2022-10-18 04:59 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.less
> +  ---gap: var(--gap);
改好了哈，目前没有发现额外的问题，麻烦大佬再看看~

2022-10-18 05:49 UTC, zqran requested changes

2022-10-18 05:49 UTC, zqran commented on src/components/image-uploader/image-uploader.tsx
> +      <Grid className={`${classPrefix}-grid`} columns={props.columns}>
这边缺少 `classPrefix` 类名，导致单测失败了

2022-10-18 07:51 UTC, miracles1919 commented on src/components/image-uploader/image-uploader.less
> +      (100vw - var(--gap) * (var(--columns) - 1)) / var(--columns)
`100vw` 是有问题的

<img width="426" alt="image" src="https://user-images.githubusercontent.com/22469543/196369245-e9fb19f9-e149-41a1-8df6-dbbe0eeca084.png">

2022-10-18 07:51 UTC, miracles1919 commented on src/components/image-uploader/index.en.md
> +### 1. The `capture` attribute is configured, but why some `Android` phones will still have the file option?
```suggestion
### The `capture` attribute is configured, but why some `Android` phones will still have the file option?
```

2022-10-18 07:51 UTC, miracles1919 commented on src/components/image-uploader/index.en.md
> +### 2. Compatibility description of the `columns` attribute
```suggestion
### Compatibility description of the `columns` attribute
```
不用加序号

2022-10-18 08:19 UTC, MuxinFeng commented on src/components/image-uploader/index.en.md
> +### 1. The `capture` attribute is configured, but why some `Android` phones will still have the file option?
好的

2022-10-18 08:19 UTC, MuxinFeng commented on src/components/image-uploader/index.en.md
> +### 2. Compatibility description of the `columns` attribute
+1

2022-10-18 09:01 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.less
> +      (100vw - var(--gap) * (var(--columns) - 1)) / var(--columns)
这个地方应该用父级元素的宽度来计算吧，也就是 `100%` 替换 `100vw`，但是我这样改组件高度直接没有了，大佬有什么想法吗

2022-10-18 09:37 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.tsx
> +      <Grid className={`${classPrefix}-grid`} columns={props.columns}>
目前在`run test`过程中发现两个问题：
1. 删除了原来的根节点，造成`image-uploader`的测试快照不一致，已通过`npm test -- -u`生成新的快照
2. `image-viewer` 有个测试用例没过，初步判断是偏移量有问题，这个我需要再看一下 `jest` 相关的文档再尝试修复。

2022-10-18 12:27 UTC, zqran commented on src/components/image-uploader/image-uploader.tsx
> +      <Grid className={`${classPrefix}-grid`} columns={props.columns}>
对于问题1，我觉得应该保留 `classPrefix ` 类名，这是 antd-mobile 组件库的规范，所有组件都自己的根类名

2022-10-19 02:05 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.tsx
> +      <Grid className={`${classPrefix}-grid`} columns={props.columns}>
那这样的话，还是要加上原来的根节点吧

2022-10-19 03:12 UTC, miracles1919 commented on src/components/image-uploader/image-uploader.less
> +      (100vw - var(--gap) * (var(--columns) - 1)) / var(--columns)
试下用 js 计算

2022-10-19 03:12 UTC, zqran commented on src/components/image-uploader/image-uploader.tsx
> +      <Grid className={`${classPrefix}-grid`} columns={props.columns}>
可以保留类名，类似：`${classPrefix} ${classPrefix}-grid` 这种形式~

2022-10-19 03:38 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.tsx
> +      <Grid className={`${classPrefix}-grid`} columns={props.columns}>
嗷嗷嗷嗷，恍然大悟

2022-10-19 03:38 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.less
> +      (100vw - var(--gap) * (var(--columns) - 1)) / var(--columns)
我试试哈

2022-10-19 11:58 UTC, MuxinFeng commented
本次 PR 难点在于无法得出栅格布局中的每个单元组件的属性，目前是通过 useSize 拿到父元素的宽度再计算得出。 @miracles1919 


目前 `code review` 发现的问题已解决，实现过程中的一点疑问跟大佬们沟通下：
1. 在 `space` 和 `grid` 之外加上了根节点（也是其他组件的一贯风格>.<），这会造成样式看起来稍微有点繁琐，但如果不加这个根元素，就无法通过 `useSize` 获取容器的宽度； @zqran 
2. 最终渲染组件时，传入 `props` 的方式没那么优雅。之前试过在 `useEffect` 里更改 `props.style` ，但是触发了重新渲染后，`props` 又重新变成默认值`const props = mergeProps(defaultProps, p)`。后来又想到用 `state` 存储 `props`，但这样又会造成图片最后一张无法删除的问题，所以最终采取了这种写法。

<img width="608" alt="image" src="https://user-images.githubusercontent.com/46584765/196683652-6002e0b7-a6a6-4bde-95ec-eace07e7467b.png">

2022-10-20 12:52 UTC, miracles1919 reviewed
另外 cell-size 的大小除了跟 container 相关外，`--gap-horizontal` 和 `--cell-size` 应该是关联的：
- 改了 `--cell-size`,  `--gap` 就要变化
- 改了 `--gap`,  `--cell-size` 就要变化

2022-10-20 12:52 UTC, miracles1919 commented on src/components/image-uploader/image-uploader.tsx
> +        Number(props.style?.['--gap-horizontal']?.replace('px', '')) || 12
css 的单位不只是 px，可能还有 rem vw，可以用 `measureCSSLength`，参考：https://github.com/ant-design/ant-design-mobile/blob/master/src/components/picker-view/wheel.tsx#L53

2022-10-20 12:52 UTC, miracles1919 commented on src/components/image-uploader/image-uploader.tsx
> +    <div className={classPrefix} ref={containerRef}>
```suggestion
    <div className={classPrefix} ref={containerRef} style={style}>
```

2022-10-21 02:01 UTC, MuxinFeng commented
> cell-size 的大小除了跟 container 相关外，`--gap-horizontal` 和 `--cell-size` 应该是关联的：
> 
> * 改了 `--cell-size`,  `--gap` 就要变化
> * 改了 `--gap`,  `--cell-size` 就要变化

我觉得在 `grid` 布局下，就不能指定 `--cell-size` 了，因为容器的宽度一定，`--gap-horizontal` 也是一定的（要么指定，要么默认用 `--gap`），这样里面的`--cell-size` 也就固定下来了

2022-10-21 02:34 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.tsx
> +    <div className={classPrefix} ref={containerRef}>
其实这里的 `extraStyle` 主要是一个 `--cell-size` 属性，放在 style 里会有类型错误哈

2022-10-21 02:43 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.tsx
> +    <div className={classPrefix} ref={containerRef}>
其实这里的 `extraStyle` 主要是一个 `--cell-size` 属性，放在 style 里会有类型错误哈

2022-10-21 02:54 UTC, miracles1919 commented on src/components/image-uploader/image-uploader.tsx
> +    <div className={classPrefix} ref={containerRef}>
所以 style 需要额外的 ts 定义，ref：https://github.com/ant-design/ant-design-mobile/blob/master/src/components/tag/tag.tsx#L42

2022-10-21 02:59 UTC, MuxinFeng commented on src/components/image-uploader/image-uploader.tsx
> +    <div className={classPrefix} ref={containerRef}>
好滴

2022-10-21 03:42 UTC, MuxinFeng commented
done

2022-10-24 04:04 UTC, miracles1919 commented
在你的基础上调整了一下

- `--cell-size` 的计算逻辑
- `--gap` 两种布局都能支持，所以就不限制了
- 更新了下文档

2022-10-24 04:51 UTC, MuxinFeng commented
> 在你的基础上调整了一下
> 
> * `--cell-size` 的计算逻辑
> * `--gap` 两种布局都能支持，所以就不限制了
> * 更新了下文档

感谢大佬，get 很多新知识

2022-10-27 09:10 UTC, zombieJ commented on src/components/image-uploader/demos/demo2.tsx
> +      <DemoBlock title='自定义列数'>
这边加一下描述，如果设置了 columns，cell size 会失效，而会根据空间自动变化。

2022-10-27 09:25 UTC, MuxinFeng commented on src/components/image-uploader/demos/demo2.tsx
> +      <DemoBlock title='自定义列数'>
<img width="487" alt="image" src="https://user-images.githubusercontent.com/46584765/198246866-e1a12fdc-e336-4a69-bef4-855424d1a2f1.png">
这个在 FAQ 里加了哈，这是是要重复强调一下吗

2022-10-27 09:41 UTC, zombieJ commented on src/components/image-uploader/image-uploader.tsx
> +  const renderChildren = () => {
这边看起来不需要做成 function，直接：
```tsx
const contentNode = (
  <>
    {...}
  </>
);
```

下面直接：
```tsx
<Grid ...>
   ...
   {contentNode}
</Grid>
```

2022-10-27 09:42 UTC, zombieJ commented on src/components/image-uploader/index.zh.md
> +`columns` 属性依赖 [Grid](./grid) 布局，该属性存在时，不支持自定义 `--cell-size` 属性，因为图片和上传按钮的大小是自动计算的。
上面 Demo 也需要注明一下，不用看到的这么远的描述。

2022-10-27 11:02 UTC, MuxinFeng commented
done @zombieJ

2022-10-27 15:17 UTC, awmleer commented on src/components/image-uploader/index.zh.md
> +| --gap-vertical   | 垂直方向的间距大小   | `var(--gap)` |
```suggestion
| --cell-size      | 图片和上传按钮的大小（仅在 columns 模式下有效） | `80px`       |
| --gap            | 间距大小（仅在非 columns 模式下有效）            | `12px`       |
| --gap-horizontal | 水平方向的间距大小（仅在非 columns 模式下有效）   | `var(--gap)` |
| --gap-vertical   | 垂直方向的间距大小（仅在非 columns 模式下有效）   | `var(--gap)` |
```

或许也可以这样注明

2022-10-27 15:31 UTC, MuxinFeng commented
done @awmleer 大佬辛苦啦

2022-10-27 16:00 UTC, miracles1919 commented on src/components/image-uploader/index.zh.md
> +| --gap-vertical   | 垂直方向的间距大小   | `var(--gap)` |
@awmleer 这里我调整了一下，`Space` 也能支持 `gap` 

https://github.com/ant-design/ant-design-mobile/pull/5728/files#diff-5a0391155d29fdbc3ab571bf6c9500de0e42125489e5f1ec6bfffe76dd42c62aR11-R15

2022-10-31 02:43 UTC, MuxinFeng commented
应该只需要改下 --cell-size 的说明哈，commit 已提交 @miracles1919 @awmleer

2022-10-31 09:52 UTC, zombieJ commented
conflict 了

2022-10-31 11:43 UTC, MuxinFeng commented
> conflict 了

好啦，真是好事多磨啊，求再看看

2022-11-01 03:14 UTC, jlala commented
正好也给了我点思路 幸运

2022-11-02 09:30 UTC, zombieJ approved these changes

2022-11-02 09:30 UTC, zombieJ commented
approved. Base 改一下到 feature 哈~

2022-11-02 09:33 UTC, MuxinFeng commented
> approved. Base 改一下到 feature 哈~

rebase 一下 feature 分支是吧

2022-11-02 09:58 UTC, MuxinFeng commented
> approved. Base 改一下到 feature 哈~

才反应过来，done 啦

2022-11-03 02:05 UTC, zqran requested changes

2022-11-03 02:05 UTC, zqran commented on src/components/image-uploader/index.zh.md
> +| columns             | 行展示数                                                                      | `number`
```suggestion
| columns             | 列数                                                                      | `number`                                                                                                   | -         |
```

`columns` 不是列吗？

2022-11-03 02:31 UTC, MuxinFeng commented on src/components/image-uploader/index.zh.md
> +| columns             | 行展示数                                                                      | `number`
好嘞，抄 Selector 那边忘了检查了，回头我提个 pr 改下另一边的

2022-11-07 15:13 UTC, merged

2022-11-07 15:14 UTC, miracles1919 commented
合并了，辛苦了 ~