fix(result-page): allow details to be null
ant-design/ant-design-mobile pull request #6354
Opened 2023-09-07 11:44 UTC by kongmoumou

-----
<a href="https://stackblitz.com/~/github/kongmoumou/ant-design-mobile/tree/fix-result-page-detail"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/kongmoumou/ant-design-mobile/tree/fix-result-page-detail)._

2023-09-07 11:59 UTC, miracles1919 commented
details 的类型是不是也增加一下？

2023-09-08 13:12 UTC, 1587315093 commented on src/components/result-page/result-page.tsx
> +  details: [] as ResultPageDetails | null | undefined,
https://github.com/ant-design/ant-design-mobile/blob/master/src/components/result-page/result-page.tsx#L42

看details这里好像没有null呀，为啥as null

2023-09-08 15:21 UTC, kongmoumou commented on src/components/result-page/result-page.tsx
> +  details: [] as ResultPageDetails | null | undefined,
mergeProps 后 details 类型只剩 `ResultPageDetails` 了

2023-09-09 14:01 UTC, 1587315093 commented on src/components/result-page/result-page.tsx
> +  details: [] as ResultPageDetails | null | undefined,
加类型的意思应该是 ResultPageProps 里加，不是 defaultProps 这个去 as 吧

2023-09-10 08:01 UTC, kongmoumou commented on src/components/result-page/result-page.tsx
> +  details: [] as ResultPageDetails | null | undefined,
ResultPageProps & defaultProps 就只剩 `ResultPageDetails`，加在 ResultPageProps 上没用， 只能通过 as 显式声明 null | undefined。或者大佬有别的办法么 🤔️

ResultPageProps & defaultProps demo ⬇️
https://www.typescriptlang.org/play?#code/C4TwDgpgBAJhBmBDArgG2ABQE4HsxQF4oBvAKClgmEQEtUBnALinuCxoDsBzAbQF1SAX1KlQkKGFz4iZCnGp16Afmat23flAA+UDmlTaoyDnHicIMISLHQAthCxcI2PIQlSoAMkpI0mKSIAxjgcrBLM9o7OHjLCYAB08rQMpAD0qRQAekqkQA

2023-09-15 06:34 UTC, 1587315093 commented on src/components/result-page/result-page.tsx
> +  details: [] as ResultPageDetails | null | undefined,
应该就是ResultPageProps 那里的 details 类型 ResultPageDetails | null 就行了，不用或undefined，加了可选 ? 可选参数会自己加 | undefined

2023-09-15 08:33 UTC, kongmoumou commented on src/components/result-page/result-page.tsx
> +  details: [] as ResultPageDetails | null | undefined,
get, done～

2023-09-15 10:11 UTC, 1587315093 approved these changes

2023-09-18 07:11 UTC, zombieJ commented on src/components/result-page/result-page.tsx
> +        {details?.length ? (
test case?

2023-09-21 04:35 UTC, 1587315093 commented
需要你来个 test case ~

2023-09-21 04:38 UTC, 1587315093 requested changes
需要你来个 test case ~

2023-10-02 13:19 UTC, kongmoumou commented
New PR for test https://github.com/ant-design/ant-design-mobile/pull/6387

@1587315093

2023-10-07 01:37 UTC, closed without merging